name: zeno
description: "A Productivity Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  # infrastructure
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  sqflite: ^2.4.2
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.1.0
  firebase_auth: ^6.1.4

  cupertino_icons: ^1.0.8
  get_it: ^8.2.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  bloc: ^9.0.1
  android_alarm_manager_plus: ^5.0.0
  permission_handler: ^12.0.1
  flutter_local_notifications: ^19.5.0
  audioplayers: ^6.5.1
  timezone: ^0.10.1
  intl: ^0.20.2
  flutter_liquid_glass_plus: ^0.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

assets:
 - .env
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
